In [6]:
import os, csv
import numpy as np
import torch

# Reading RPM #
with open('/workspace/data/Diagram_Coordinates/1D_rpm.csv', 'r', encoding='utf-8-sig') as f:  # 使用'utf-8-sig'来自动处理BOM
    data = list(csv.reader(f, delimiter=","))        
RPM = np.array(data)
RPM = np.float32(RPM)

select_seq = RPM[:6, [1, 3, 5]]
print(select_seq)
RPM_X = select_seq[:, ::-1]
print(RPM_X)
RPM_Y = select_seq[:, 0::]
print(RPM_Y)

[[24. 25. 28.]
 [37. 42. 42.]
 [21. 28. 29.]
 [12. 17. 21.]
 [21. 24. 27.]
 [37. 40. 42.]]
[[28. 25. 24.]
 [42. 42. 37.]
 [29. 28. 21.]
 [21. 17. 12.]
 [27. 24. 21.]
 [42. 40. 37.]]
[[24. 25. 28.]
 [37. 42. 42.]
 [21. 28. 29.]
 [12. 17. 21.]
 [21. 24. 27.]
 [37. 40. 42.]]


In [8]:
time_series_list = [12, 24, 32]
for t in range(3-1, -1, -1):
    print(time_series_list[t])

32
24
12


In [2]:
import os, csv
import numpy as np
import torch

# Reading RPM #
with open('/workspace/data/Diagram_Coordinates/1D_rpm.csv', 'r', encoding='utf-8-sig') as f:  # 使用'utf-8-sig'来自动处理BOM
    data = list(csv.reader(f, delimiter=","))        
RPM = np.array(data)
RPM = np.float32(RPM)

select_seq = RPM[5, [1, 3, 5, 7]]
RPM_X = select_seq[:-1]
print(RPM_X)
RPM_Y = select_seq[1:]
print(RPM_Y)

[37. 40. 42.]
[40. 42. 41.]


In [25]:
RPM_X_tensor = torch.Tensor(RPM_X)
RPM_Y_tensor = torch.Tensor(RPM_Y)
RPM_X_tensor.cuda()
RPM_Y_tensor.cuda()

tensor([[25., 28., 28.],
        [42., 42., 40.],
        [28., 29., 27.],
        [17., 21., 17.],
        [24., 27., 25.]], device='cuda:0')

In [9]:
test_x_rpm = np.random.rand(1, 7) 
test_x_rpm

array([[0.83645042, 0.53475235, 0.72372967, 0.8460796 , 0.54394486,
        0.96691868, 0.66363474]])

In [1]:
for t in range(3):
    print(t)

0
1
2


In [3]:
for t in range(3-1, -1, -1): 
    print(t)

2
1
0
